### ISSUE TITLE
GC

### ISSUE THREAD

**Issue by Ye-Tian-Zero** [joker-qi/WiscKey#7]
> 在垃圾回收器的设计上，现在是用db_->Get来判断vlog中某个kv对是否有效，但其实这个过程完全没有必要。只需要在合并过程中，记录需要删除的kv对信息，在垃圾回收过程中参照这些信息进行垃圾回后即可。现在的做法对IO影响应该会很大

假设把删除的key都放在filea内，但是每次GC没法确保所有的filea内的key 都回收了。所以filea大概率越写越大，或者说filea本身就需要GC？

**Comment by guo-shaoge** [comment]
你说的对的。这是个失误😅。因为不是很严肃的项目，就一直拖着没改




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            597654481
                            
                            
                                
                                    邮箱：597654481@qq.com
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master


On 11/16/2018 15:54, skilxnTL wrote: 在垃圾回收器的设计上，现在是用db_->Get来判断vlog中某个kv对是否有效，但其实这个过程完全没有必要。只需要在合并过程中，记录需要删除的kv对信息，在垃圾回收过程中参照这些信息进行垃圾回后即可。现在的做法对IO影响应该会很大
这个做法，又需要涉及GC记录删除的kv对的文件。感觉引入的复杂度过高啊。

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/joker-qi/ndslDB","title":"joker-qi/ndslDB","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/joker-qi/ndslDB"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"GC (#7)"}],"action":{"name":"View Issue","url":"https://github.com/joker-qi/ndslDB/issues/7"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/joker-qi/ndslDB/issues/7",
"url": "https://github.com/joker-qi/ndslDB/issues/7",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "GC (#7)",
"sections": [
{
"text": "",
"activityTitle": "**skilxnTL**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@skilxnTL",
"facts": [
{
"name": "Repository: ",
"value": "joker-qi/ndslDB"
},
{
"name": "Issue #: ",
"value": 7
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"joker-qi/ndslDB\",\n\"issueId\": 7,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"joker-qi/ndslDB\",\n\"issueId\": 7\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/joker-qi/ndslDB/issues/7"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 412528235\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by Ye-Tian-Zero** [comment]
不过定期做全量GC应该可以解决这个问题，据我了解HBASE的MOB就是这么做的。
